export const studyList = [
  {
    id: 1,
    title: "K.K.의 UX 스터디",
    days: 62,
    description: "나비보벳따우",
    points: 310,
    reactions: { study: 37, fire: 26, heart: 14 },
    color: "green",
  },
  {
    id: 2,
    title: "연욱의 개발공장",
    days: 104,
    description: "Slow and steady wins the race!",
    points: 510,
    reactions: { study: 42, fire: 29, heart: 22 },
    color: "yellow",
  },
  {
    id: 3,
    title: "하늘의 디자인 연구소",
    days: 87,
    description: "작지만 꾸준한 변화가 완성도를 만든다.",
    points: 420,
    reactions: { study: 55, fire: 31, heart: 28 },
    color: "blue",
  },
  {
    id: 4,
    title: "민재의 알고리즘 마스터",
    days: 45,
    description: "문제를 풀며 사고력을 키우자!",
    points: 280,
    reactions: { study: 33, fire: 19, heart: 11 },
    color: "green",
  },
  {
    id: 5,
    title: "지은의 영어 리딩 클럽",
    days: 73,
    description: "하루 한 문장으로 영어 감각을 기르자.",
    points: 360,
    reactions: { study: 48, fire: 24, heart: 16 },
    color: "yellow",
  },
  {
    id: 6,
    title: "현수의 데이터 분석 스터디",
    days: 120,
    description: "데이터는 거짓말하지 않는다.",
    points: 580,
    reactions: { study: 51, fire: 35, heart: 27 },
    color: "blue",
  },
  {
    id: 7,
    title: "유진의 마케팅 인사이트",
    days: 66,
    description: "소비자의 마음을 읽는 법.",
    points: 400,
    reactions: { study: 39, fire: 28, heart: 20 },
    color: "green",
  },
  {
    id: 8,
    title: "도현의 프론트엔드 부트캠프",
    days: 91,
    description: "React로 세상을 바꿔보자!",
    points: 470,
    reactions: { study: 46, fire: 33, heart: 25 },
    color: "yellow",
  },
  {
    id: 9,
    title: "서하늘의 크리에이티브",
    days: 58,
    description: "창의력은 꾸준한 연습에서 온다.",
    points: 330,
    reactions: { study: 41, fire: 23, heart: 19 },
    color: "blue",
  },
];
